source 'https://rubygems.org'

group :development do
  gem "RestfulSrvr", github: "restful-srvr/RestfulSrvr"
  gem "vagrant", github: "mitchellh/vagrant", tag: "v1.5.4"
end

group :plugins do
  gem "vagrant-RestfulSrvr", github: "restful-srvr/vagrant-RestfulSrvr"
  gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
end
